CREATE DATABASE IF NOT EXISTS artsyDB;
USE artsyDB;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Favorites;

CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE Favorites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_email VARCHAR(100) NOT NULL,
  artist_id VARCHAR(50) NOT NULL,
  FOREIGN KEY (user_email) REFERENCES Users(email) ON DELETE CASCADE
);